### ISSUE TITLE
Use of const in strict mode (node-0.10)

### ISSUE THREAD

**Issue by strk** [sindresorhus/detect-indent-cli#1]
```
$ detect-indent 

/home/strk/.nvm/v0.10.48/lib/node_modules/detect-indent-cli/cli.js:3
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

**Comment by SamVerschueren** [comment]
Node 0.10 is deprecated. Either upgrade Node or downgrade this module.
